version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: AWSSDK.DynamoDBv2
    versions:
    - 3.5.4.22
    - 3.5.4.23
    - 3.5.4.24
    - 3.5.4.25
    - 3.5.4.26
    - 3.5.4.27
    - 3.5.4.28
    - 3.5.4.29
    - 3.5.4.30
    - 3.5.4.31
    - 3.5.4.32
    - 3.5.4.34
    - 3.5.4.35
    - 3.5.4.36
    - 3.5.4.37
    - 3.7.0
    - 3.7.0.10
    - 3.7.0.11
    - 3.7.0.12
    - 3.7.0.13
    - 3.7.0.14
    - 3.7.0.15
    - 3.7.0.2
    - 3.7.0.3
    - 3.7.0.4
    - 3.7.0.7
    - 3.7.0.8
    - 3.7.0.9
  - dependency-name: Microsoft.AspNetCore.Identity.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Identity.UI
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.EntityFrameworkCore.Relational
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.SpaServices.Extensions
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.AspNetCore.ApiAuthorization.IdentityServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
