version: "3.8"

services:
  dynamodb:
    container_name: dynamodb
    build:
      context: ./docker-setup/dynamodb
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks: 
      fsdn_network:

  dynamodb-admin:
    image:  aaronshaf/dynamodb-admin
    container_name: dynamodb-ui
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=http://dynamodb:8000"
    networks: 
      fsdn_network:

networks:
  fsdn_network: