version: "3.8"

services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"

  dynamodb-admin:
    image:  aaronshaf/dynamodb-admin
    container_name: dynamodb-ui
    ports:
      - "8001:8001"
    environment:
      - "DYNAMO_ENDPOINT=http://dynamodb:8000"